# 公開するページのURL
baseURL = "https://www.chocola.top/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "ちょこみんとのおうち"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Rise_chocolate"
    bio = "VRChatでのびのびしているちょこみんと。普段は家でごろごろしてる。"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#00F2FF"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "rise_love_vr"
  github = "Risechocolate"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

